/*
 error propagation test
*/
import 'std.errors'
import 'std.io'

fun a {
    return result.ok(10)
}

fun b {
    return result.err('error found')
}

fun c {
    a_val := a()?
    io.println('a: ' + a_val)
    b_val := b()?
    io.println('b: ' + b_val)
}

io.println(c().unwrap_err())