import 'std.errors'

type File(raw_handle) {
    fun init {
        self.is_open := true
    }

    fun __ensure_open {
        if self.is_open == false {
            panic('Attempted to write to closed file!')
        }
    }

	fun write(data) {
        self.__ensure_open()

		res := fs.__internal_write(self.raw_handle, data)

		if res == 0 {
			return result.ok(null)
		}

		return result.err(res)
	}

    fun close {
        // fs.__internal_close(self.raw_handle)

        self.is_open = false
        self.raw_handle = null
    }
	
    fun read_to_string() {
        self.__ensure_open()

        data := fs.__internal_read_to_string(self.raw_handle)

        if data == null {
            return result.err(1)
        }

        return result.ok(data)
    }
}

unit fs {
    native __internal_open -> 'fs@open'
    native __internal_create -> 'fs@create'
    native __internal_write -> 'fs@write'
    // native __internal_close -> 'fs@close'
    native __internal_read_to_string -> 'fs@read_to_string'

	fun create(filename) {
		file_hdl := __internal_create(filename)

		if file_hdl == null {
			return result.err(1)
		}

		return result.ok(new File(file_hdl))
	}

    fun open(filename) {
        file_hdl := __internal_open(filename)

        if file_hdl == null {
            return result.err(1)
        }

        return result.ok(new File(file_hdl))
    }
}
